start: sourse.o Lift.o LiftDriver.o Cabin.o LiftShaft.o PeopleGroup.o 
	g++ -o start  sourse.o Lift.o LiftDriver.o Cabin.o LiftShaft.o PeopleGroup.o 

Lift.o:Lift.cpp
	g++ -c Lift.cpp

Cabin.o:Cabin.cpp
	g++ -c Cabin.cpp

LiftDriver.o:LiftDriver.cpp
	g++ -c LiftDriver.cpp

LiftShaft.o:LiftShaft.cpp
	g++ -c LiftShaft.cpp

PeopleGroup.o:PeopleGroup.cpp
	g++ -c PeopleGroup.cpp

sourse.o:sourse.cpp
	g++ -c sourse.cpp
clean:
	rm -rf *.o